### ISSUE TITLE
Review 1.0

### ISSUE THREAD

**Issue by theaspect** [PetrSed/SE-2020-Spring#1]
1. Сессию необходимо добавлять в коллекцию которая прокинута в сервис снаружи https://github.com/PetrSed/SE-2020-Spring/blob/v1.01/src/services/AccountingService.kt#L7
2. Вот эта проверка должна быть внутри enum https://github.com/PetrSed/SE-2020-Spring/blob/v1.01/src/Handler.kt#L43 более того не стоит руками перечислять поля enum используй метод values
3. В папке исходников не должно быть скриптов https://github.com/PetrSed/SE-2020-Spring/blob/v1.01/src/test.sh

**Comment by ArtBekk** [comment]
Все пункты исправлены.
